apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: careertrojan
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: backend-api
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/your-org/careertrojan-backend:dev
  - target:
      kind: Deployment
      name: web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/your-org/careertrojan-web:dev
