"""initial_schema

Revision ID: 4bb22efad373
Revises: 
Create Date: 2026-02-26 17:00:31.676988
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bb22efad373'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('role_function_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('classification_keywords', sa.JSON(), nullable=True),
    sa.Column('seniority_indicators', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_function_definitions_function_code'), 'role_function_definitions', ['function_code'], unique=True)
    op.create_index(op.f('ix_role_function_definitions_id'), 'role_function_definitions', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('otp_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('application_blockers',
    sa.Column('blocker_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resume_id', sa.String(), nullable=True),
    sa.Column('jd_id', sa.String(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('blocker_type', sa.String(), nullable=True),
    sa.Column('blocker_category', sa.String(), nullable=True),
    sa.Column('requirement_text', sa.String(), nullable=True),
    sa.Column('gap_description', sa.String(), nullable=True),
    sa.Column('criticality_score', sa.Float(), nullable=True),
    sa.Column('severity_level', sa.String(), nullable=True),
    sa.Column('impact_on_application', sa.Float(), nullable=True),
    sa.Column('detected_by', sa.String(), nullable=True),
    sa.Column('detection_method', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence_data', sa.JSON(), nullable=True),
    sa.Column('is_addressable', sa.Boolean(), nullable=True),
    sa.Column('improvement_timeline', sa.String(), nullable=True),
    sa.Column('improvement_difficulty', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('blocker_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consent_type', sa.String(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_id'), 'consent_records', ['id'], unique=False)
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('credit_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('action_name', sa.String(), nullable=True),
    sa.Column('credits_consumed', sa.Integer(), nullable=False),
    sa.Column('credits_remaining_after', sa.Integer(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_usage_log_action_id'), 'credit_usage_log', ['action_id'], unique=False)
    op.create_index(op.f('ix_credit_usage_log_created_at'), 'credit_usage_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_usage_log_id'), 'credit_usage_log', ['id'], unique=False)
    op.create_index(op.f('ix_credit_usage_log_user_id'), 'credit_usage_log', ['user_id'], unique=False)
    op.create_table('data_export_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_export_requests_id'), 'data_export_requests', ['id'], unique=False)
    op.create_index(op.f('ix_data_export_requests_user_id'), 'data_export_requests', ['user_id'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interactions_action_type'), 'interactions', ['action_type'], unique=False)
    op.create_index(op.f('ix_interactions_created_at'), 'interactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_interactions_id'), 'interactions', ['id'], unique=False)
    op.create_index(op.f('ix_interactions_session_id'), 'interactions', ['session_id'], unique=False)
    op.create_index(op.f('ix_interactions_user_id'), 'interactions', ['user_id'], unique=False)
    op.create_table('interview_question_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_function_id', sa.Integer(), nullable=False),
    sa.Column('question_category', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_purpose', sa.Text(), nullable=True),
    sa.Column('sample_answer_framework', sa.Text(), nullable=True),
    sa.Column('interviewer_insight', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('source_attribution', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_function_id'], ['role_function_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_question_bank_id'), 'interview_question_bank', ['id'], unique=False)
    op.create_index(op.f('ix_interview_question_bank_question_category'), 'interview_question_bank', ['question_category'], unique=False)
    op.create_index(op.f('ix_interview_question_bank_role_function_id'), 'interview_question_bank', ['role_function_id'], unique=False)
    op.create_table('mentor_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_applications_id'), 'mentor_applications', ['id'], unique=False)
    op.create_table('mentors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_mentors_id'), 'mentors', ['id'], unique=False)
    op.create_table('ninety_day_plan_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_function_id', sa.Integer(), nullable=False),
    sa.Column('seniority_level', sa.String(length=50), nullable=True),
    sa.Column('template_name', sa.String(length=200), nullable=False),
    sa.Column('focus_areas', sa.JSON(), nullable=True),
    sa.Column('day_30_actions', sa.JSON(), nullable=True),
    sa.Column('day_30_success_metric', sa.Text(), nullable=True),
    sa.Column('day_60_actions', sa.JSON(), nullable=True),
    sa.Column('day_60_success_metric', sa.Text(), nullable=True),
    sa.Column('day_90_actions', sa.JSON(), nullable=True),
    sa.Column('day_90_success_metric', sa.Text(), nullable=True),
    sa.Column('smart_reports', sa.JSON(), nullable=True),
    sa.Column('closing_statement', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_function_id'], ['role_function_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ninety_day_plan_templates_id'), 'ninety_day_plan_templates', ['id'], unique=False)
    op.create_index(op.f('ix_ninety_day_plan_templates_role_function_id'), 'ninety_day_plan_templates', ['role_function_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('promo_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_created_at'), 'payment_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_gateway_transaction_id'), 'payment_transactions', ['gateway_transaction_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_user_id'), 'payment_transactions', ['user_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('gateway_subscription_id', sa.String(), nullable=True),
    sa.Column('gateway_customer_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('next_billing_date', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_gateway_subscription_id'), 'subscriptions', ['gateway_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('user_credit_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_tier', sa.String(), nullable=False),
    sa.Column('credits_total', sa.Integer(), nullable=False),
    sa.Column('credits_remaining', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_credit_balances_id'), 'user_credit_balances', ['id'], unique=False)
    op.create_index(op.f('ix_user_credit_balances_user_id'), 'user_credit_balances', ['user_id'], unique=True)
    op.create_table('user_interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('detected_role_function_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_role_function_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('questions_asked', sa.JSON(), nullable=True),
    sa.Column('answers_given', sa.JSON(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('ai_feedback_summary', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_role_function_id'], ['role_function_definitions.id'], ),
    sa.ForeignKeyConstraint(['detected_role_function_id'], ['role_function_definitions.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interview_sessions_id'), 'user_interview_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_interview_sessions_user_id'), 'user_interview_sessions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('blocker_improvement_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('blocker_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_title', sa.String(), nullable=True),
    sa.Column('plan_description', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('resource_name', sa.String(), nullable=True),
    sa.Column('resource_provider', sa.String(), nullable=True),
    sa.Column('resource_url', sa.String(), nullable=True),
    sa.Column('resource_cost', sa.Float(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Integer(), nullable=True),
    sa.Column('estimated_completion_weeks', sa.Integer(), nullable=True),
    sa.Column('expected_improvement_score', sa.Float(), nullable=True),
    sa.Column('priority_rank', sa.Integer(), nullable=True),
    sa.Column('ai_recommendation_score', sa.Float(), nullable=True),
    sa.Column('success_probability', sa.Float(), nullable=True),
    sa.Column('milestones_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blocker_id'], ['application_blockers.blocker_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('mentorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('mentee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentorships_id'), 'mentorships', ['id'], unique=False)
    op.create_table('user_ninety_day_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('job_title_text', sa.String(length=255), nullable=True),
    sa.Column('company_text', sa.String(length=255), nullable=True),
    sa.Column('customized_day_30', sa.JSON(), nullable=True),
    sa.Column('customized_day_60', sa.JSON(), nullable=True),
    sa.Column('customized_day_90', sa.JSON(), nullable=True),
    sa.Column('customized_reports', sa.JSON(), nullable=True),
    sa.Column('personal_closing_statement', sa.Text(), nullable=True),
    sa.Column('is_exported', sa.Boolean(), nullable=True),
    sa.Column('export_format', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['ninety_day_plan_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ninety_day_plans_id'), 'user_ninety_day_plans', ['id'], unique=False)
    op.create_index(op.f('ix_user_ninety_day_plans_user_id'), 'user_ninety_day_plans', ['user_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentorship_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_table('mentor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('note_type', sa.String(), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('note_title', sa.String(), nullable=True),
    sa.Column('is_shared_with_user', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['mentorships.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_notes_id'), 'mentor_notes', ['id'], unique=False)
    op.create_table('requirement_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentorship_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('mentor_signed', sa.Boolean(), nullable=True),
    sa.Column('user_signed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentorship_id'], ['mentorships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_documents_id'), 'requirement_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_documents_id'), table_name='requirement_documents')
    op.drop_table('requirement_documents')
    op.drop_index(op.f('ix_mentor_notes_id'), table_name='mentor_notes')
    op.drop_table('mentor_notes')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_user_ninety_day_plans_user_id'), table_name='user_ninety_day_plans')
    op.drop_index(op.f('ix_user_ninety_day_plans_id'), table_name='user_ninety_day_plans')
    op.drop_table('user_ninety_day_plans')
    op.drop_index(op.f('ix_mentorships_id'), table_name='mentorships')
    op.drop_table('mentorships')
    op.drop_table('blocker_improvement_plans')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_interview_sessions_user_id'), table_name='user_interview_sessions')
    op.drop_index(op.f('ix_user_interview_sessions_id'), table_name='user_interview_sessions')
    op.drop_table('user_interview_sessions')
    op.drop_index(op.f('ix_user_credit_balances_user_id'), table_name='user_credit_balances')
    op.drop_index(op.f('ix_user_credit_balances_id'), table_name='user_credit_balances')
    op.drop_table('user_credit_balances')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_gateway_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_payment_transactions_user_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_gateway_transaction_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_created_at'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_ninety_day_plan_templates_role_function_id'), table_name='ninety_day_plan_templates')
    op.drop_index(op.f('ix_ninety_day_plan_templates_id'), table_name='ninety_day_plan_templates')
    op.drop_table('ninety_day_plan_templates')
    op.drop_index(op.f('ix_mentors_id'), table_name='mentors')
    op.drop_table('mentors')
    op.drop_index(op.f('ix_mentor_applications_id'), table_name='mentor_applications')
    op.drop_table('mentor_applications')
    op.drop_index(op.f('ix_interview_question_bank_role_function_id'), table_name='interview_question_bank')
    op.drop_index(op.f('ix_interview_question_bank_question_category'), table_name='interview_question_bank')
    op.drop_index(op.f('ix_interview_question_bank_id'), table_name='interview_question_bank')
    op.drop_table('interview_question_bank')
    op.drop_index(op.f('ix_interactions_user_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_session_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_id'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_created_at'), table_name='interactions')
    op.drop_index(op.f('ix_interactions_action_type'), table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_data_export_requests_user_id'), table_name='data_export_requests')
    op.drop_index(op.f('ix_data_export_requests_id'), table_name='data_export_requests')
    op.drop_table('data_export_requests')
    op.drop_index(op.f('ix_credit_usage_log_user_id'), table_name='credit_usage_log')
    op.drop_index(op.f('ix_credit_usage_log_id'), table_name='credit_usage_log')
    op.drop_index(op.f('ix_credit_usage_log_created_at'), table_name='credit_usage_log')
    op.drop_index(op.f('ix_credit_usage_log_action_id'), table_name='credit_usage_log')
    op.drop_table('credit_usage_log')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('application_blockers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_function_definitions_id'), table_name='role_function_definitions')
    op.drop_index(op.f('ix_role_function_definitions_function_code'), table_name='role_function_definitions')
    op.drop_table('role_function_definitions')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
