-- IntelliCV-AI Mentorship Portal Database Schema
-- Week 1 Implementation - November 15, 2025
-- Privacy-protected mentor-user linking system with payment workflow

SET timezone = 'UTC';

-- ============================================================================
-- MENTORSHIP CONNECTIONS (ANONYMOUS LINKING)
-- ============================================================================

CREATE TABLE IF NOT EXISTS mentorship_links (
    link_id VARCHAR(20) PRIMARY KEY,              -- e.g. "LINK_12345"
    user_id VARCHAR(50) NOT NULL,                 -- Internal user ID
    mentor_id VARCHAR(50) NOT NULL,               -- Internal mentor ID
    program_id VARCHAR(50),                       -- Mentorship program (optional)
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('pending', 'active', 'paused', 'completed', 'cancelled')),
    anonymous_name VARCHAR(100),                  -- e.g. "Mentee #12345"
    completion_date TIMESTAMP WITH TIME ZONE,

    -- Privacy: Mentor sees ONLY anonymous_name and link_id
    CONSTRAINT unique_mentorship UNIQUE(user_id, mentor_id, program_id)
);

-- Index for mentor lookups (show all their mentees)
CREATE INDEX IF NOT EXISTS idx_mentorship_mentor ON mentorship_links(mentor_id, status);

-- Index for user lookups (show all their mentors)
CREATE INDEX IF NOT EXISTS idx_mentorship_user ON mentorship_links(user_id, status);

COMMENT ON TABLE mentorship_links IS 'Anonymous mentor-user connections - mentors never see personal data';
COMMENT ON COLUMN mentorship_links.link_id IS 'Anonymous identifier shown to mentor (e.g. LINK_12345)';
COMMENT ON COLUMN mentorship_links.anonymous_name IS 'Display name for mentor (e.g. Mentee #12345)';

-- ============================================================================
-- MENTOR NOTES (SESSION NOTES)
-- ============================================================================

CREATE TABLE IF NOT EXISTS mentor_notes (
    note_id SERIAL PRIMARY KEY,
    link_id VARCHAR(20) NOT NULL REFERENCES mentorship_links(link_id) ON DELETE CASCADE,
    mentor_id VARCHAR(50) NOT NULL,
    note_type VARCHAR(50) DEFAULT 'session',      -- session, requirement, progress, observation, ai_generated
    note_title VARCHAR(200),
    note_content TEXT,
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    is_shared_with_user BOOLEAN DEFAULT FALSE,    -- Can user see this note?
    session_date DATE,                            -- When was the session this note refers to?

    CONSTRAINT fk_mentor_notes_link FOREIGN KEY (link_id) REFERENCES mentorship_links(link_id)
);

-- Index for mentor's view (all notes for their mentees)
CREATE INDEX IF NOT EXISTS idx_notes_link ON mentor_notes(link_id, created_date DESC);

-- Index for mentor's dashboard (recent notes)
CREATE INDEX IF NOT EXISTS idx_notes_mentor ON mentor_notes(mentor_id, created_date DESC);

COMMENT ON TABLE mentor_notes IS 'Session notes and observations linked to anonymous connections';
COMMENT ON COLUMN mentor_notes.is_shared_with_user IS 'If true, user can see this note in their portal';

-- ============================================================================
-- REQUIREMENT DOCUMENTS (FORMAL AGREEMENTS)
-- ============================================================================

CREATE TABLE IF NOT EXISTS requirement_documents (
    doc_id SERIAL PRIMARY KEY,
    link_id VARCHAR(20) NOT NULL REFERENCES mentorship_links(link_id) ON DELETE CASCADE,
    mentor_id VARCHAR(50) NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    document_title VARCHAR(200) DEFAULT 'Mentorship Requirement Document',
    document_content TEXT,                        -- Markdown format generated by AI
    generated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    user_signed_off BOOLEAN DEFAULT FALSE,
    user_signoff_date TIMESTAMP WITH TIME ZONE,
    user_signature TEXT,                          -- Digital signature / confirmation
    mentor_signed_off BOOLEAN DEFAULT FALSE,
    mentor_signoff_date TIMESTAMP WITH TIME ZONE,
    mentor_signature TEXT,
    version INT DEFAULT 1,
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'pending_user', 'pending_mentor', 'signed', 'rejected', 'superseded')),
    rejection_reason TEXT,

    CONSTRAINT fk_req_docs_link FOREIGN KEY (link_id) REFERENCES mentorship_links(link_id)
);

-- Index for user's view (their agreements)
CREATE INDEX IF NOT EXISTS idx_req_docs_user ON requirement_documents(user_id, status);

-- Index for mentor's view (their agreements)
CREATE INDEX IF NOT EXISTS idx_req_docs_mentor ON requirement_documents(mentor_id, status);

-- Index for link history (all versions)
CREATE INDEX IF NOT EXISTS idx_req_docs_link ON requirement_documents(link_id, version DESC);

COMMENT ON TABLE requirement_documents IS 'Formal mentorship agreements requiring both parties to sign off';
COMMENT ON COLUMN requirement_documents.status IS 'draft=being edited, pending_user=awaiting user, pending_mentor=awaiting mentor, signed=both signed, rejected=needs revision';

-- ============================================================================
-- INVOICES (PAYMENT WORKFLOW)
-- ============================================================================

CREATE TABLE IF NOT EXISTS invoices (
    invoice_id SERIAL PRIMARY KEY,
    link_id VARCHAR(20) NOT NULL REFERENCES mentorship_links(link_id) ON DELETE CASCADE,
    mentor_id VARCHAR(50) NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    invoice_number VARCHAR(50) UNIQUE,            -- e.g. "INV-2025-11-12345"
    service_description TEXT,                     -- What is being charged for
    amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
    currency VARCHAR(3) DEFAULT 'USD',            -- ISO 4217: USD, GBP, EUR, etc.
    platform_fee DECIMAL(10,2) NOT NULL,          -- 20% of amount
    mentor_portion DECIMAL(10,2) NOT NULL,        -- 80% of amount
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'held', 'released', 'disputed', 'refunded', 'cancelled')),
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    paid_date TIMESTAMP WITH TIME ZONE,
    released_date TIMESTAMP WITH TIME ZONE,
    stripe_payment_intent_id VARCHAR(100),        -- Stripe integration
    stripe_charge_id VARCHAR(100),

    CONSTRAINT fk_invoices_link FOREIGN KEY (link_id) REFERENCES mentorship_links(link_id)
);

-- Index for mentor earnings tracking
CREATE INDEX IF NOT EXISTS idx_invoices_mentor ON invoices(mentor_id, status, created_date DESC);

-- Index for user payment history
CREATE INDEX IF NOT EXISTS idx_invoices_user ON invoices(user_id, status, created_date DESC);

-- Index for admin monitoring
CREATE INDEX IF NOT EXISTS idx_invoices_admin ON invoices(status, created_date DESC);

COMMENT ON TABLE invoices IS 'Payment invoices - Platform holds funds and releases after completion';
COMMENT ON COLUMN invoices.status IS 'pending=awaiting payment, paid=user paid, held=platform holding, released=mentor paid, disputed=mediation needed';
COMMENT ON COLUMN invoices.platform_fee IS 'Always 20% of amount';
COMMENT ON COLUMN invoices.mentor_portion IS 'Always 80% of amount';

-- ============================================================================
-- FUND RELEASES (COMPLETION TRACKING & MEDIATION)
-- ============================================================================

CREATE TABLE IF NOT EXISTS fund_releases (
    release_id SERIAL PRIMARY KEY,
    invoice_id INTEGER NOT NULL REFERENCES invoices(invoice_id) ON DELETE CASCADE,
    link_id VARCHAR(20) NOT NULL REFERENCES mentorship_links(link_id) ON DELETE CASCADE,
    mentor_delivered BOOLEAN DEFAULT FALSE,       -- Did mentor complete the service?
    mentor_delivery_date TIMESTAMP WITH TIME ZONE,
    user_confirmed BOOLEAN DEFAULT FALSE,         -- Did user confirm satisfaction?
    user_confirmation_date TIMESTAMP WITH TIME ZONE,
    release_date TIMESTAMP WITH TIME ZONE,
    dispute_raised BOOLEAN DEFAULT FALSE,
    dispute_date TIMESTAMP WITH TIME ZONE,
    dispute_description TEXT,
    dispute_resolution TEXT,
    mediator_admin_id VARCHAR(50),                -- Which admin mediated
    resolution_outcome VARCHAR(50) CHECK (resolution_outcome IN ('refund_user', 'pay_mentor', 'partial_refund', 'hold_pending', NULL)),

    CONSTRAINT fk_fund_releases_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id),
    CONSTRAINT fk_fund_releases_link FOREIGN KEY (link_id) REFERENCES mentorship_links(link_id)
);

-- Index for admin mediation dashboard
CREATE INDEX IF NOT EXISTS idx_fund_releases_disputes ON fund_releases(dispute_raised, dispute_date DESC) WHERE dispute_raised = TRUE;

-- Index for payment processing
CREATE INDEX IF NOT EXISTS idx_fund_releases_invoice ON fund_releases(invoice_id);

COMMENT ON TABLE fund_releases IS 'Tracks completion status and dispute resolution for fund releases';
COMMENT ON COLUMN fund_releases.mentor_delivered IS 'Mentor marks service as delivered';
COMMENT ON COLUMN fund_releases.user_confirmed IS 'User confirms satisfaction with service';
COMMENT ON COLUMN fund_releases.dispute_raised IS 'Either party can raise a dispute';

-- ============================================================================
-- MENTOR APPLICATIONS (USER REGISTRATION)
-- ============================================================================

CREATE TABLE IF NOT EXISTS mentor_applications (
    application_id SERIAL PRIMARY KEY,
    applicant_user_id VARCHAR(50) NOT NULL,       -- User applying to become mentor
    email VARCHAR(255) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    phone VARCHAR(50),
    linkedin_url TEXT,

    -- Professional background (Step 1)
    industry VARCHAR(100),
    specialization VARCHAR(200),
    years_experience INT CHECK (years_experience >= 0),
    current_role VARCHAR(200),
    current_company VARCHAR(200),

    -- Mentorship expertise (Step 2)
    expertise_areas JSONB,                        -- Array of expertise areas
    target_audience JSONB,                        -- Array: ["junior", "mid", "senior", "exec"]
    session_formats JSONB,                        -- Array: ["1-on-1", "group", "hybrid"]
    hours_per_week INT,

    -- Package design (Step 3)
    initial_packages JSONB,                       -- Array of package objects
    ai_focus_tags JSONB,                          -- AI recommendations captured during intake
    ai_chat_history JSONB,                        -- Transcript of mentor AI intake assistant
    application_snapshot JSONB,                   -- Structured payload for admin review
    source VARCHAR(50) DEFAULT 'user_portal',     -- Submission origin

    -- Application status
    status VARCHAR(50) DEFAULT 'submitted' CHECK (status IN ('submitted', 'under_review', 'approved', 'rejected', 'pending_info')),
    submitted_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    reviewed_date TIMESTAMP WITH TIME ZONE,
    reviewer_admin_id VARCHAR(50),                -- Guardian who reviewed
    review_notes TEXT,
    rejection_reason TEXT,

    -- Mentor activation
    mentor_id VARCHAR(50),                        -- Assigned upon approval
    activated_date TIMESTAMP WITH TIME ZONE,

    CONSTRAINT unique_application_user UNIQUE(applicant_user_id)
);

-- Index for guardian review queue
CREATE INDEX IF NOT EXISTS idx_applications_status ON mentor_applications(status, submitted_date DESC);

-- Index for user lookup (check if already applied)
CREATE INDEX IF NOT EXISTS idx_applications_user ON mentor_applications(applicant_user_id);

COMMENT ON TABLE mentor_applications IS 'User applications to become mentors - Guardian review workflow';
COMMENT ON COLUMN mentor_applications.status IS 'submitted → under_review → approved/rejected';
COMMENT ON COLUMN mentor_applications.mentor_id IS 'Generated upon approval - grants mentor portal access';

-- ============================================================================
-- MENTOR PAYOUT DETAILS (BANK TRANSFER INFORMATION)
-- ============================================================================

CREATE TABLE IF NOT EXISTS mentor_payout_details (
    payout_id SERIAL PRIMARY KEY,
    mentor_id VARCHAR(50) UNIQUE NOT NULL,        -- One set of details per mentor

    -- Bank account details
    account_holder_name VARCHAR(200) NOT NULL,
    bank_name VARCHAR(200),
    account_number VARCHAR(100),                  -- Encrypted in production
    routing_number VARCHAR(50),                   -- For US (ABA/ACH)
    swift_code VARCHAR(20),                       -- For international
    iban VARCHAR(50),                             -- For EU/international
    sort_code VARCHAR(10),                        -- For UK

    -- Address for compliance
    billing_address TEXT,
    city VARCHAR(100),
    state_province VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(3),                           -- ISO 3166-1 alpha-3 (USA, GBR, DEU, etc.)

    -- Payout preferences
    preferred_currency VARCHAR(3) DEFAULT 'USD',  -- ISO 4217
    payout_method VARCHAR(20) DEFAULT 'bank_transfer' CHECK (payout_method IN ('bank_transfer', 'paypal', 'stripe', 'wise')),
    payout_email VARCHAR(255),                    -- For PayPal/Wise

    -- Verification status
    verified BOOLEAN DEFAULT FALSE,
    verified_date TIMESTAMP WITH TIME ZONE,
    verified_by_admin_id VARCHAR(50),

    -- Timestamps
    created_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Index for mentor lookup
CREATE INDEX IF NOT EXISTS idx_payout_mentor ON mentor_payout_details(mentor_id);

-- Index for unverified accounts (admin review queue)
CREATE INDEX IF NOT EXISTS idx_payout_unverified ON mentor_payout_details(verified) WHERE verified = FALSE;

COMMENT ON TABLE mentor_payout_details IS 'Mentor bank account and payout information for fund releases';
COMMENT ON COLUMN mentor_payout_details.account_number IS 'Should be encrypted at rest in production';
COMMENT ON COLUMN mentor_payout_details.verified IS 'Admin must verify before first payout';

-- ============================================================================
-- PAYOUT TRANSACTIONS (AUDIT TRAIL)
-- ============================================================================

CREATE TABLE IF NOT EXISTS payout_transactions (
    transaction_id SERIAL PRIMARY KEY,
    mentor_id VARCHAR(50) NOT NULL,
    invoice_id INTEGER REFERENCES invoices(invoice_id),

    -- Transaction details
    amount DECIMAL(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    payout_method VARCHAR(20),                    -- bank_transfer, paypal, etc.

    -- Status tracking
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'completed', 'failed', 'cancelled')),
    initiated_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_date TIMESTAMP WITH TIME ZONE,

    -- External reference
    external_transaction_id VARCHAR(100),         -- Stripe payout ID, bank reference, etc.
    failure_reason TEXT,

    -- Admin tracking
    initiated_by_admin_id VARCHAR(50),

    CONSTRAINT fk_payout_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id)
);

-- Index for mentor payout history
CREATE INDEX IF NOT EXISTS idx_payout_mentor ON payout_transactions(mentor_id, initiated_date DESC);

-- Index for status monitoring
CREATE INDEX IF NOT EXISTS idx_payout_status ON payout_transactions(status, initiated_date DESC);

COMMENT ON TABLE payout_transactions IS 'Audit trail of all payouts to mentors';
COMMENT ON COLUMN payout_transactions.status IS 'pending → processing → completed/failed';

-- ============================================================================
-- TRIGGERS FOR AUTO-CALCULATIONS
-- ============================================================================

-- Auto-calculate platform fee and mentor portion on invoice creation
CREATE OR REPLACE FUNCTION calculate_invoice_split()
RETURNS TRIGGER AS $$
BEGIN
    NEW.platform_fee := ROUND(NEW.amount * 0.20, 2);  -- 20%
    NEW.mentor_portion := ROUND(NEW.amount * 0.80, 2); -- 80%
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_calculate_invoice_split
    BEFORE INSERT OR UPDATE OF amount ON invoices
    FOR EACH ROW
    EXECUTE FUNCTION calculate_invoice_split();

-- Auto-generate anonymous name on link creation
CREATE OR REPLACE FUNCTION generate_anonymous_name()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.anonymous_name IS NULL THEN
        -- Extract number from link_id (e.g. "LINK_12345" → "12345")
        NEW.anonymous_name := 'Mentee #' || SUBSTRING(NEW.link_id FROM 6);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_generate_anonymous_name
    BEFORE INSERT ON mentorship_links
    FOR EACH ROW
    EXECUTE FUNCTION generate_anonymous_name();

-- ============================================================================
-- INITIAL DATA / SAMPLE CONFIGURATION
-- ============================================================================

-- Note: Add sample data in separate file (04-mentorship-test-data.sql)

-- ============================================================================
-- GRANTS (Adjust based on your user roles)
-- ============================================================================

-- Grant permissions to application user (adjust username as needed)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO intellicv_app;
-- GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO intellicv_app;

-- ============================================================================
-- SCHEMA VERSION TRACKING
-- ============================================================================

INSERT INTO system_config (config_key, config_value, description)
VALUES (
    'mentorship_schema_version',
    '{"version": "1.0", "deployed": "2025-11-15", "week": "Week 1"}'::jsonb,
    'Mentorship portal database schema version'
)
ON CONFLICT (config_key) DO UPDATE
SET config_value = EXCLUDED.config_value,
    updated_at = CURRENT_TIMESTAMP;

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
