#!/usr/bin/env python3
"""
merge_additional_data.py  –  Phase 4e batch 2
Ingests terms from:
  - "more data for glossary.txt"  (Manufacturing Glossary + Stock Market vocabulary)
  - "more data 2.txt"             (Oil & Gas downstream roles + Oil & Gas glossary
                                    + IT Jargon + Mechanical Engineering glossary
                                    + Accounting/Finance terminology + Product Mgmt glossary)

Maps terms into existing gazetteers. Does NOT overwrite – merges with dedup + sort.
Syncs L: → C: after every save.
"""

import json, pathlib, shutil, re
from typing import Dict, List, Set

# ── paths ────────────────────────────────────────────────────────────────────
GAZ_L = pathlib.Path(r"L:\antigravity_version_ai_data_final\ai_data_final\gazetteers")
GAZ_C = pathlib.Path(r"C:\careertrojan\ai_data_final\gazetteers")

# ── Manufacturing Glossary terms (from "more data for glossary.txt") ─────────
MFG_MANUFACTURING = [
    "approved manufacturer list", "AML",
    "advanced product quality planning", "APQP",
    "approved vendor list", "AVL",
    "bill of materials", "BOM", "BOM level",
    "computer aided design", "CAD",
    "corrective action protective action", "CAPA",
    "corrective action request", "CAR",
    "change management process", "change order", "change request",
    "child item", "parent item",
    "contract manufacturer", "CM",
    "compliance", "compliance mark",
    "document change request", "DCR",
    "design history file", "DHF",
    "device history record", "DHR",
    "device master record", "DMR",
    "document control",
    "engineering bill of materials", "EBOM",
    "electrical computer aided design", "ECAD",
    "engineering change notice", "ECN",
    "engineering change order", "ECO",
    "engineering change request", "ECR",
    "electronic design automation", "EDA",
    "enterprise resource planning", "ERP",
    "field failure request", "FFR",
    "form fit function", "FFF",
    "good manufacturing practice", "GMP",
    "international traffic in arms regulations", "ITAR",
    "just in time", "JIT",
    "kanban",
    "made to spec",
    "manufacturing bill of materials", "MBOM",
    "mechanical computer aided design", "MCAD",
    "manufacturing change order", "MCO",
    "manufacturing change request", "MCR",
    "manufacturing deviation",
    "manufacturing execution system", "MES",
    "manufacturing work instructions", "MWI",
    "multi level BOM",
    "new product development", "NPD",
    "new product introduction", "NPI",
    "original equipment manufacturer", "OEM",
    "off the shelf",
    "part name", "part number",
    "product data management", "PDM",
    "product data exchange", "PDX",
    "product lifecycle management", "PLM",
    "procurement type",
    "product record", "prototype",
    "quality management system", "QMS",
    "redline", "reference designator",
    "requirement", "revision", "revision control",
    "restriction of hazardous substances", "RoHS",
    "return material authorization", "RMA",
    "supplier corrective action request", "SCAR",
    "scrubbing a BOM", "single level BOM",
    "stock keeping unit", "SKU",
    "standard operating procedure", "SOP",
    "time to market", "TTM",
    "unit of measure", "UOM",
    "waste electrical and electronic equipment", "WEEE",
    "item master", "markup",
]

# ── Stock Market / Finance vocabulary (from "more data for glossary.txt") ────
STOCK_MARKET_FINANCE = [
    "ask price", "bid price", "blue chip stocks",
    "dividend", "stock issue", "leverage",
    "margin", "spread", "slump", "spike", "tumble",
    "bond", "cash market", "day trading",
    "expense ratio", "index funds", "mutual fund",
    "market order", "price to earnings ratio",
    "target date fund", "averaging down",
    "bear market", "bull market", "beta coefficient",
    "going long", "short selling", "haircut",
    "moving average", "opening price", "pink sheet stocks",
    "rally", "volatility", "volume", "yield",
    "broker", "arbitrage", "portfolio",
    "securities", "stock exchange", "stock market",
    "initial public offering", "IPO",
    "commodities", "debenture", "earnings per share",
    "floatation", "growth stocks", "liquidity",
    "speculation", "buyout",
    "boom", "crash", "dip", "drift",
    "close price", "index",
]

# ── Oil & Gas downstream roles (from "more data 2.txt") ─────────────────────
OIL_GAS_JOB_TITLES = [
    "refinery manager", "plant manager",
    "operations superintendent",
    "board operator", "console operator",
    "outside operator", "field operator",
    "shift lead", "shift supervisor",
    "product scheduler", "logistics coordinator",
    "process engineer", "reliability engineer",
    "asset integrity engineer",
    "project engineer", "CAPEX manager",
    "process safety engineer", "PSM coordinator",
    "optimization engineer",
    "maintenance superintendent",
    "I&E technician", "instrumentation and electrical technician",
    "millwright",
    "pipefitter", "welder",
    "planner scheduler",
    "quality control chemist", "QC chemist",
    "R&D scientist", "lab technician",
    "environmental specialist",
    "industrial hygienist",
    "safety coordinator",
    "tool pusher", "drilling superintendent",
    "roughneck", "roustabout", "land man",
]

# ── Oil & Gas glossary (from "more data 2.txt") ─────────────────────────────
OIL_GAS_TERMS = [
    "abandon", "abatement", "acreage",
    "annulus", "appraisal well", "aquifer", "azimuth",
    "barrel", "bit", "bitumen", "block",
    "blow down", "blow out", "borehole",
    "blow out preventer", "BOP", "brine",
    "casing", "casing string", "casinghead gas",
    "catalytic cracking",
    "carbon capture and storage", "CCS",
    "cementing", "christmas tree",
    "commercial field", "completion",
    "compressor station", "condensate",
    "conventional resources",
    "coring", "core barrel", "cracker",
    "crude oil", "cuttings",
    "derrick", "development phase",
    "deviated well", "directional drilling",
    "downstream", "drilling", "drilling rig",
    "dry gas", "dry hole",
    "enhanced oil recovery", "EOR",
    "environmental assessment",
    "equivalent barrels", "ethylene",
    "estimated ultimate recovery", "EUR",
    "exploration drilling", "exploration well",
    "field", "fishing", "flaring",
    "flowback water", "formation", "formation pressure",
    "hydraulic fracturing", "fracking",
    "fracturing fluid", "fugitive emissions",
    "geographic information systems", "GIS",
    "greenhouse gas", "GHG",
    "global warming potential", "GWP",
    "gusher", "heavy oil",
    "held by production",
    "horizontal drilling", "hydrocarbon",
    "hydrostatic pressure",
    "impoundment", "independent operator",
    "infill wells", "injection well",
    "integrated company", "jacket",
    "lay barge", "life cycle analysis", "LCA",
    "liquefied natural gas", "LNG",
    "liquefied petroleum gas", "LPG",
    "mechanical integrity test",
    "methane", "midstream", "mineral rights",
    "moonpool", "mud", "drilling fluids",
    "natural gas", "natural gas liquids",
    "net acres", "oil in place", "oil pool",
    "oilfield services", "operator",
    "payzone", "permeability", "petroleum",
    "pipeline inspection gauge", "PIG",
    "pipeline", "play", "platform",
    "plugging of well", "pooling",
    "porosity", "possible reserves",
    "primary recovery", "probable reserves",
    "processing plant", "produced water",
    "production well", "propane",
    "proven field", "proven reserves",
    "recompletion", "recoverable reserves",
    "refinery", "reserves", "reservoir",
    "rig", "rig up", "rig down",
    "riser", "royalty payment",
    "seal formation",
    "secondary recovery",
    "shale", "shale gas", "shale oil",
    "shut in well", "shutdown",
    "sour gas", "source rock",
    "spacing", "spud in",
    "stripper production",
    "surface reclamation",
    "suspended well",
    "tension leg platform",
    "tight gas", "topsides", "trap",
    "unconventional reservoirs",
    "upstream", "well", "wellhead",
    "wellhead revenues", "well log",
    "wet gas", "wellbore", "workover",
    "loss of primary containment",
    "turnaround", "TAR",
    "distributed control system", "DCS",
    "permit to work", "lockout tagout", "LOTO",
    "hot work permit",
    "crude slate", "linear programming model",
    "ASTM International",
]

# ── IT / Cybersecurity Jargon (from "more data 2.txt") ──────────────────────
IT_TECH_SKILLS = [
    "antivirus", "artificial intelligence", "AI",
    "advanced micro devices", "AMD",
    "algorithm", "application programming interface", "API",
    "adware", "basic input output system", "BIOS",
    "botnet", "backdoor", "bandwidth",
    "business continuity",
    "cache", "cloud computing",
    "cryptocurrency", "cyberattack",
    "cyber essentials",
    "cybersecurity", "dark web",
    "data breach",
    "distributed denial of service", "DDoS",
    "decryption", "disaster recovery",
    "digital transformation",
    "domain name system", "DNS",
    "encryption", "edge computing",
    "firewall", "firewall as a service", "FaaS",
    "file transfer protocol", "FTP",
    "graphical user interface", "GUI",
    "HTML", "hypertext markup language",
    "IP address", "internet service provider", "ISP",
    "Java", "JavaScript",
    "key logger", "local area network", "LAN",
    "Linux",
    "malware", "managed service provider", "MSP",
    "Microsoft Azure",
    "network address translation", "NAT",
    "network operating system", "NOS",
    "open source", "operating system",
    "phishing", "ransomware",
    "random access memory", "RAM",
    "router", "server", "software",
    "spyware", "search engine optimization", "SEO",
    "TCP IP", "trojan horse",
    "two factor authentication", "2FA",
    "user experience", "UX",
    "virtual private network", "VPN",
    "voice over internet protocol", "VoIP",
    "wide area network", "WAN",
    "wireless local area network", "WLAN",
    "extensible markup language", "XML",
    "anything as a service", "XaaS",
    "YAML", "zero day vulnerability",
    "transport layer security", "TLS",
    "secure sockets layer", "SSL",
    "certificate authority",
    "quantum computing",
    "quality of service", "QoS",
    "password management",
    "vulnerability management",
]

# ── Mechanical Engineering terms (from "more data 2.txt" Wikipedia) ──────────
MECH_ENGINEERING = [
    "abrasion", "absolute zero",
    "accelerated life testing",
    "acceleration", "accelerometer",
    "accuracy and precision",
    "acoustic droplet ejection",
    "active cooling", "actual mechanical advantage",
    "aerodynamics", "agitator",
    "air handler", "air compressor",
    "air conditioner", "air preheater",
    "airflow", "allowance",
    "applied mechanics",
    "Archimedes screw",
    "automaton clock", "automobile handling",
    "automotive engineering",
    "babbitt metal", "backlash",
    "balancing machine", "ball detent",
    "ball screw", "ball spline",
    "Beale number", "bearing",
    "bearing pressure", "bearing surface",
    "belt friction", "bending",
    "biomechatronics", "body in white",
    "bogie", "bonded seal",
    "brittleness", "buckling",
    "bushing", "boiler",
    "carbon fiber reinforced polymer", "CFRP",
    "classical mechanics",
    "clean room design", "clevis fastener",
    "clutch", "CNC",
    "coefficient of thermal expansion",
    "coil spring", "combustion",
    "composite material", "compression ratio",
    "compressive strength",
    "computational fluid dynamics", "CFD",
    "computer aided design",
    "computer aided manufacturing", "CAM",
    "computer numerical control",
    "conservation of mass",
    "constant velocity joint", "CV joint",
    "continuum mechanics", "control theory",
    "corrosion", "crankshaft",
    "damping ratio", "deformation",
    "delamination",
    "design for manufacturability", "DFM",
    "diesel engine", "differential gear",
    "dimensionless number",
    "driveshaft", "dynamics",
    "dynamometer", "elasticity",
    "electric motor",
    "electrical engineering",
    "finite element analysis", "FEA",
    "flywheel", "force", "forging",
    "four bar linkage", "four stroke cycle",
    "friction", "gear", "gear ratio",
    "gear coupling",
    "heat engine", "heat transfer",
    "Hookes law", "hydraulics",
    "hydrostatics",
    "ideal mechanical advantage",
    "inclined plane", "inertia",
    "instrumentation",
    "kinematic determinacy", "kinematics",
    "laser", "leaf spring", "lever",
    "linkage", "lubrication",
    "machine learning",
    "mechanical advantage",
    "mechanical efficiency",
    "mechanical engineering",
    "mechatronics",
    "microelectromechanical systems", "MEMS",
    "moment of inertia",
    "nanotechnology",
    "nozzle", "Ohms law",
    "Pascals law", "piston",
    "plain bearing", "plasticity",
    "pneumatics", "Poissons ratio",
    "power", "pressure",
    "process control",
    "pulley", "pump",
    "quality control", "quality assurance",
    "rack and pinion",
    "reliability engineering",
    "reverse engineering",
    "rheology", "rigid body",
    "robotics", "roller chain",
    "rotordynamics",
    "safety engineering",
    "shear strength", "shear stress",
    "simple machine",
    "solid mechanics", "solid modeling",
    "statics", "stress strain curve",
    "structural failure",
    "suspension system",
    "technical drawing",
    "tensile strength", "tensile stress",
    "thermodynamics",
    "torque", "torsion spring",
    "toughness", "tribology",
    "turbine", "valve",
    "vibration", "viscosity",
    "wear", "wedge",
    "wheel and axle",
    "yield point", "yield strength",
    "Youngs modulus",
    "zero defects",
]

# ── Accounting / Finance terms (from "more data 2.txt" — NYSSCPA guide) ─────
ACCOUNTING_FINANCE = [
    "401k plan", "absorption costing",
    "accelerated depreciation",
    "account payable", "account receivable",
    "accountable plan",
    "accounting change", "accounting cycle",
    "accounts payable subsidiary ledger",
    "accounts receivable turnover",
    "accrual", "accrual accounting", "accrual basis",
    "accrued expense", "accrued interest",
    "accumulated depreciation",
    "acid test ratio", "acquisition",
    "additional paid in capital",
    "adjusted basis", "adjusted gross income",
    "adjusted trial balance",
    "adverse opinion",
    "alternative minimum tax", "AMT",
    "American Institute of Certified Public Accountants", "AICPA",
    "amortization", "annual report",
    "annuity", "appreciation",
    "asset", "asset turnover",
    "audit", "audit risk", "audit sampling",
    "auditors report",
    "balance sheet", "bank reconciliation",
    "bankruptcy", "beginning inventory",
    "beta coefficient",
    "board of directors",
    "bond discount", "bond indenture",
    "book value", "bookkeeping",
    "bottom line", "break even point",
    "budget", "burden rate",
    "business combinations", "business segment",
    "cafeteria plan",
    "capital asset pricing model", "CAPM",
    "capital expenditure", "capital gain",
    "capital stock", "capitalize",
    "capitalized cost", "capitalized interest",
    "capitalized lease", "carrying value",
    "cash basis", "cash dividend",
    "cash equivalents", "cash flow",
    "cash flow to assets", "cash flow to sales",
    "certificate of deposit",
    "certified public accountant", "CPA",
    "chief executive officer", "CEO",
    "chief financial officer", "CFO",
    "closing entry",
    "collateral", "collateralized mortgage obligation", "CMO",
    "commercial paper", "common stock",
    "comparative financial statement",
    "compilation", "compliance audit",
    "compound interest",
    "comprehensive income",
    "confirmation", "conservatism",
    "consistency", "consolidated financial statements",
    "contingent liability",
    "continuing professional education", "CPE",
    "contra account",
    "contributed capital", "contribution margin",
    "control risk",
    "conversion", "convertible stock",
    "copyright", "corporate bond",
    "corporate income tax",
    "corporation", "cost accounting",
    "cost basis", "cost of capital",
    "cost of goods sold",
    "cost recovery method",
    "coupon rate", "coupon bond",
    "credit", "credit agreement",
    "creditor", "current asset",
    "current liability", "current ratio",
    "current value", "current yield",
    "declining balance method",
    "default", "deferral",
    "deferred income taxes",
    "defined benefit plan", "defined contribution plan",
    "deflation", "demand loan",
    "depletion", "depreciation",
    "derivatives", "detection risk",
    "direct labor costs", "direct material",
    "direct overhead", "disbursement",
    "disclaimer of opinion", "disclosure",
    "discontinued operations",
    "discount rate", "discounted cash flow",
    "disposable income",
    "dividend payout ratio",
    "dividends in arrears",
    "double entry bookkeeping",
    "double taxation",
    "earned income", "earnings per share", "EPS",
    "effective interest rate",
    "effective tax rate",
    "employee benefit plan",
    "employee stock ownership plan", "ESOP",
    "encumbrance", "ending inventory",
    "equity", "equity financing",
    "equity method of accounting",
    "equity securities",
    "escrow", "estate tax",
    "estimated tax",
    "excise tax", "exemption",
    "expenditure", "expense",
    "expense ratio",
    "face value", "factoring",
    "factory overhead costs",
    "fair market value",
    "FASB", "Financial Accounting Standards Board",
    "federal income taxes",
    "federal reserve system",
    "fiduciary", "FIFO", "first in first out",
    "financial leverage",
    "financial statements",
    "finished goods inventory",
    "fiscal year", "fixed annuity",
    "fixed assets", "fixed costs",
    "forecasting", "foreclosure",
    "foreign currency translation",
    "foreign tax credit",
    "form 10K", "form 10Q", "form 8K",
    "franchise", "franchise tax",
    "fraud", "free cash flow",
    "freight in", "freight out",
    "full disclosure", "fund accounting",
    "GAAP", "generally accepted accounting principles",
    "GAAS", "generally accepted auditing standards",
    "gain", "general journal", "general ledger",
    "general partnership",
    "gift tax", "going concern",
    "goodwill", "gross income",
    "gross margin", "gross sales",
    "guaranty",
    "half life",
    "held to maturity security",
    "historical cost", "holding period",
    "income statement",
    "income tax basis",
    "incremental cash flow",
    "individual retirement account", "IRA",
    "inflation", "inflation rate",
    "initial public offering",
    "insolvency", "installment method",
    "intangible asset",
    "interest coverage ratio",
    "interest rate",
    "interim financial statements",
    "internal audit", "internal control",
    "internal rate of return",
    "internal revenue code",
    "internal revenue service", "IRS",
    "inventory", "inventory turnover",
    "investment", "investment banker",
    "investment income",
    "joint venture",
    "journal entry", "junk bonds",
    "just in time inventory",
    "Keogh plan", "key employee",
    "last in first out", "LIFO",
    "lease", "leasehold",
    "ledger", "letter of credit",
    "letter of intent",
    "leverage", "leveraged buy out",
    "leveraged lease",
    "liability", "lien",
    "limited liability", "limited liability company", "LLC",
    "limited liability partnership", "LLP",
    "limited partnership",
    "liquid assets", "liquidation",
    "liquidity", "liquidity ratio",
    "loan", "long term debt",
    "long term investment",
    "lower of cost or market",
    "lump sum distribution",
    "macroeconomics", "management accounting",
    "managerial accounting",
    "marginal cost", "marginal tax rate",
    "mark to market",
    "market capitalization",
    "market interest rate", "market price",
    "market share", "market value",
    "marketable securities",
    "matching principle",
    "material weakness", "materiality",
    "maturity date",
    "merchandise inventory",
    "merger",
    "microeconomics",
    "modified accelerated cost recovery system",
    "money laundering",
    "money market", "monopoly",
    "mortgage", "municipal bond",
    "mutual fund",
    "NASDAQ",
    "net asset value", "NAV",
    "net current assets", "net income",
    "net loss", "net present value", "NPV",
    "net proceeds", "net sales", "net worth",
    "New York Stock Exchange", "NYSE",
    "no par stock",
    "non sufficient funds check", "NSF",
    "not for profit organization",
    "notes payable", "notes receivable",
    "operating cycle", "operating expense",
    "operating lease", "operating profit",
    "opportunity cost",
    "ordinary income",
    "paid in capital", "par value",
    "parent company", "partnership",
    "passive income", "payback period",
    "payout ratio",
    "peer review",
    "pension", "periodic inventory system",
    "perpetual inventory",
    "personal financial planning",
    "personal property", "petty cash",
    "preferred stock", "premium bond",
    "prepaid expense", "present value",
    "price earnings ratio",
    "prime rate", "principal",
    "private placement",
    "pro forma", "pro rata",
    "profit", "profit margin",
    "profit sharing plan",
    "promissory note",
    "property plant and equipment",
    "proprietorship", "prospectus",
    "proxy", "public offering",
    "purchase order",
    "qualified opinion",
    "quick assets", "quick ratio",
    "rate of return", "ratio analysis",
    "real estate investment trust", "REIT",
    "real income", "real interest rate",
    "receivable turnover",
    "recession", "reconciliation",
    "redemption value", "refinancing",
    "regression analysis",
    "regulated investment company",
    "reinsurance",
    "related party transaction",
    "retained earnings",
    "return on assets", "return on equity",
    "return on investment", "ROI",
    "return on sales",
    "revenue recognition",
    "S corporation",
    "safe harbor rule",
    "sale leaseback",
    "salvage value", "savings bond",
    "SEC", "Securities and Exchange Commission",
    "securitization",
    "sensitivity analysis",
    "sinking fund",
    "solvency", "standard cost",
    "standard deduction",
    "standard deviation",
    "stock compensation plan",
    "stock exchange", "stock options",
    "stock split",
    "stockholders equity",
    "straight line depreciation",
    "subsequent event",
    "subsidiary",
    "sum of the years digits",
    "target costing", "tax basis",
    "tax court", "tax credit",
    "tax lien", "tax shelter",
    "tax year", "taxable income",
    "time value of money",
    "total capitalization",
    "total cost",
    "total quality management", "TQM",
    "trade date", "trademark",
    "transfer price", "transfer tax",
    "treasury bill", "treasury bond",
    "treasury note", "treasury stock",
    "trial balance",
    "troubled debt restructuring",
    "trust", "trustee",
    "unearned income",
    "uniform capitalization rules",
    "unlimited liability",
    "unqualified opinion",
    "valuation", "valuation allowance",
    "value added tax", "VAT",
    "variable costs",
    "variable rate loan",
    "venture capital",
    "vertical analysis",
    "vesting", "working capital",
    "working papers",
    "yield curve", "yield to maturity",
    "zero coupon bond",
    "PAYE", "corporation tax",
    "self assessment", "HMRC",
    "financial year", "opening balance",
    "closing balance", "payroll",
    "debtors", "deductibles",
    "remittance",
]

# ── Product Management terms (from "more data 2.txt") ────────────────────────
PRODUCT_MGMT = [
    "A/B testing", "backlog",
    "churn rate", "conversion rate",
    "cross functional team",
    "epic", "feature creep",
    "go to market strategy", "GTM strategy",
    "iteration",
    "key performance indicator", "KPI",
    "lean product development",
    "market segmentation",
    "minimum viable product", "MVP",
    "persona", "product lifecycle",
    "product vision", "roadmap",
    "scrum", "sprint",
    "stakeholder",
    "user experience", "UX",
    "user story",
    "value proposition",
    "wireframe",
]

# ── Additional abbreviations to ensure coverage ─────────────────────────────
EXTRA_ABBREVIATIONS = [
    "AML", "APQP", "AVL", "BOM", "CAD", "CAPA", "CAR",
    "CM", "DCR", "DHF", "DHR", "DMR", "EBOM", "ECAD",
    "ECN", "ECO", "ECR", "EDA", "ERP", "FFR", "FFF",
    "GMP", "ITAR", "JIT", "MBOM", "MCAD", "MCO", "MCR",
    "MES", "MWI", "NPD", "NPI", "OEM", "PDM", "PDX",
    "PLM", "QMS", "RMA", "RoHS", "SCAR", "SKU", "SOP",
    "TTM", "UOM", "WEEE",
    "BOP", "CCS", "EOR", "EUR", "GIS", "GHG", "GWP",
    "LCA", "LNG", "LPG", "PIG", "DCS", "LOTO", "TAR",
    "BIOS", "DDoS", "DNS", "FTP", "GUI", "ISP", "LAN",
    "MSP", "NAT", "NOS", "RAM", "SEO", "TLS", "SSL",
    "VPN", "VoIP", "WAN", "WLAN", "XML", "XaaS", "QoS",
    "2FA", "FaaS",
    "CFD", "CFRP", "CNC", "DFM", "FEA", "MEMS",
    "AMT", "AICPA", "CAPM", "CPA", "CEO", "CFO",
    "CMO", "CPE", "EPS", "ESOP", "FASB", "FIFO",
    "GAAP", "GAAS", "IRA", "IRS", "LIFO", "LLC", "LLP",
    "NASDAQ", "NAV", "NPV", "NYSE", "NSF", "REIT",
    "ROI", "SEC", "TQM", "VAT", "PAYE", "HMRC",
    "KPI", "MVP", "GTM", "IPO",
]

# ── Additional certifications / regulatory ───────────────────────────────────
EXTRA_CERTIFICATIONS = [
    "ISO 9000", "ISO 13485", "ISO 14000",
    "RoHS compliance", "WEEE directive",
    "ITAR compliance",
    "21 CFR Part 11", "21 CFR Part 820",
    "OSHA Process Safety Management",
    "EPA compliance",
    "CE marking", "UL certification",
    "FCC certification", "CCC certification",
    "VCCI certification",
    "Cyber Essentials certification",
    "Cyber Essentials Plus",
    "PCAOB",
    "Sarbanes Oxley Act",
    "certified public accountant",
    "certified management accountant", "CMA",
    "certified internal auditor", "CIA",
    "certified financial planner", "CFP",
    "personal financial specialist", "PFS",
    "professional engineer", "PE",
]

# ── Additional methodologies ─────────────────────────────────────────────────
EXTRA_METHODOLOGIES = [
    "kanban", "just in time",
    "scrum", "agile", "sprint",
    "lean product development",
    "total quality management",
    "six sigma", "zero defects",
    "A/B testing",
    "design for manufacturability",
    "accelerated life testing",
    "value stream mapping",
    "continuous improvement",
    "PDCA cycle",
    "kaizen",
    "poka yoke",
    "5S methodology",
    "root cause analysis",
    "failure mode effects analysis", "FMEA",
    "statistical process control", "SPC",
]

# ── mapping: list → gazetteer filename ───────────────────────────────────────
CATEGORY_MAP: Dict[str, List[str]] = {
    "manufacturing.json":      MFG_MANUFACTURING,
    "financial_services.json": STOCK_MARKET_FINANCE + ACCOUNTING_FINANCE,
    "oil_gas.json":            OIL_GAS_TERMS,
    "job_titles.json":         OIL_GAS_JOB_TITLES,
    "tech_skills.json":        IT_TECH_SKILLS,
    "engineering.json":        MECH_ENGINEERING,
    "industry_terms.json":     PRODUCT_MGMT,
    "abbreviations.json":      EXTRA_ABBREVIATIONS,
    "certifications.json":     EXTRA_CERTIFICATIONS,
    "methodologies.json":      EXTRA_METHODOLOGIES,
}

# ── helpers ──────────────────────────────────────────────────────────────────
def normalize(term: str) -> str:
    """lower-strip-collapse"""
    return re.sub(r"\s+", " ", term.strip().lower())

def load_gazetteer(path: pathlib.Path) -> List[str]:
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return data.get("terms", [])
        if isinstance(data, list):
            return data
    return []

def save_gazetteer(path: pathlib.Path, terms: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"terms": terms}, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8")

def merge_terms(existing: List[str], new_terms: List[str]) -> tuple:
    seen: Set[str] = set()
    merged: List[str] = []
    for t in existing + new_terms:
        key = normalize(t)
        if key and key not in seen:
            seen.add(key)
            merged.append(t.strip())
    merged.sort(key=lambda s: s.lower())
    added = len(merged) - len(existing)
    return merged, added

def sync_file(src: pathlib.Path, dst: pathlib.Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)

# ── main ─────────────────────────────────────────────────────────────────────
def main() -> None:
    total_before = 0
    total_after  = 0

    for filename, terms in CATEGORY_MAP.items():
        src = GAZ_L / filename
        dst = GAZ_C / filename

        existing = load_gazetteer(src)
        total_before += len(existing)

        merged, added = merge_terms(existing, terms)
        total_after += len(merged)

        save_gazetteer(src, merged)
        sync_file(src, dst)

        status = f"+{added} new" if added else "no change"
        print(f"  {filename:<30s}  {len(existing):>5d} → {len(merged):>5d}  ({status})")

    # ── also sync any other json files that haven't changed ──────────────
    synced = 0
    for f in GAZ_L.glob("*.json"):
        dst = GAZ_C / f.name
        if f.name not in CATEGORY_MAP:
            sync_file(f, dst)
            synced += 1

    print(f"\n  TOTAL: {total_before} → {total_after} terms "
          f"(+{total_after - total_before} new)")
    print(f"  Synced {synced + len(CATEGORY_MAP)} files L: → C:")


if __name__ == "__main__":
    main()
